GET http://localhost:8080/doc/list?page=2&size=3
Accept: application/json
token:237160053545766912

###
GET http://localhost:8080/doc/list?name=文档1
token:237160053545766912
###
GET http://localhost:8080/doc/list
token:237160053545766912
###
GET http://localhost:8080/doc/all/1
token:237406617090527232
### 更新
POST http://localhost:8080/doc/save
Content-Type: application/json
token:237387506046341120

{
  "id": 7,
  "ebookId": 1,
  "voteCount": 100000000,
  "content": "报文段 是TCP协议的工作单元，它：封装数据：将应用数据加上TCP控制信息。分块传输：将大数据流切割成适合网络传输的块提供可靠性：通过序列号、确认、重传机制实现流量控制：通过窗口大小管理保证顺序：接收方按序列号重组数据简单来说：报文段就是TCP为了在不可靠的IP网络上实现可靠传输而创造的智能数据包。它让TCP能够像寄挂号信一样，确保每个数据块都能可靠、有序地到达目的地。"

}


###保存
POST http://localhost:8080/doc/save
Content-Type: application/json
token:237487356175847424

{
"ebookId": 1,
"parent": 0,
"name": "文档8",
  "content": "报文段 是TCP协议的工作单元，它：封装数据：将应用数据加上TCP控制信息。分块传输：将大数据流切割成适合网络传输的块提供可靠性：通过序列号、确认、重传机制实现流量控制：通过窗口大小管理保证顺序：接收方按序列号重组数据简单来说：报文段就是TCP为了在不可靠的IP网络上实现可靠传输而创造的智能数据包。它让TCP能够像寄挂号信一样，确保每个数据块都能可靠、有序地到达目的地。"

}
###
DELETE http://localhost:8080/doc/delete/7
token:237160053545766912

###批量删除
DELETE http://localhost:8080/doc/delete/1,2,3
Content-Type: application/json
token:237208252276936704

###删除单个
DELETE http://localhost:8080/doc/delete/237165055723048960
Content-Type: application/json
token:237208252276936704

###获取文本
GET http://localhost:8080/doc/find-content/237487582609543168
Accept: application/json
token:237487356175847424
###增加点赞数
POST http://localhost:8080/doc/vote/237487403688923136
Accept: application/json
token:237487356175847424