###
GET http://localhost:8080/user/list?loginName=test2(更新)
###
GET http://localhost:8080/user/list

### 更新
POST http://localhost:8080/user/save
Content-Type: application/json

{
  "id": 236462108731117568,
  "loginName": "test2(更新）",
  "name": "panda",
  "password": "test11111"
}

### 新增
POST http://localhost:8080/user/save
Content-Type: application/json

{
  "loginName": "test2",
  "name": "panda",
  "password": "test11111"
}

###
DELETE http://localhost:8080/user/delete/236462178624999424