###
GET http://localhost:8080/user/list?loginName=test2(更新)
###
GET http://localhost:8080/user/list

### 更新
POST http://localhost:8080/user/save
Content-Type: application/json

{
  "id": 236462108731117568,
  "loginName": "test2(更新）",
  "name": "panda",
  "password": "test21111"
}

### 新增
POST http://localhost:8080/user/save
Content-Type: application/json

{
  "loginName": "test2(更新）",
  "name": "panda2",
  "password": "test21111"
}
### 新增
POST http://localhost:8080/user/save
Content-Type: application/json


{
  "loginName": "test5",
  "name": "panda5",
  "password": "test11111"
}

###
DELETE http://localhost:8080/user/delete/236462178624999424

### 修改密码
POST http://localhost:8080/user/reset-password
Content-Type: application/json

{
  "id": 236462108731117568,
  "password": "test31111"
}

### 登录
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "loginName": "test2(更新）",
  "password": "test31111"
}

###登出
GET http://localhost:8080/user/loginout/237118550035271680

###